# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 294ecef0e11e544b92c27a2e1804be63bf216e070141ac53dc3bcd37e065b773613a79e645e2fcac56de8418660df0b9bb52d5f30a0134bdfa61dd3573f8e56e

test:
  secret_key_base: 8c9d9931bf75a28820ddc8ab5447de45a7635666be5252e584502cde527c981e8d493d047031c44382003ad75250ffdd2bcc6ce3ad9094888fa06c021833b5e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
